#!/usr/bin/env python3
"""
Skill scaffold generator.

Creates the correct directory structure and boilerplate for a new skill,
following the spec in references/spec.md.

Usage:
    python create_skill.py "skill-name" "One sentence description." [--category utility]
    python create_skill.py "log-analyzer" "Triage Kubernetes pod crash logs." --category utility
"""

import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path


SKILLS_ROOT = Path.home() / ".gemini" / "antigravity" / "skills"

CATEGORIES = ["utility", "finalization", "initialization", "planning", "analysis", "meta"]


def to_kebab(name: str) -> str:
    """Normalise name to kebab-case. Raises if result is invalid."""
    kebab = re.sub(r"[\s_]+", "-", name.strip().lower())
    kebab = re.sub(r"[^a-z0-9-]", "", kebab)
    kebab = re.sub(r"-+", "-", kebab).strip("-")
    if not kebab:
        raise ValueError(f"Cannot derive a valid kebab-case name from: {name!r}")
    if kebab != name.strip().lower().replace("_", "-").replace(" ", "-"):
        print(f"  Note: name normalised to '{kebab}'")
    return kebab


def create_skill(name: str, description: str, category: str, dry_run: bool = False) -> Path:
    skill_name = to_kebab(name)
    skill_dir = SKILLS_ROOT / skill_name
    today = date.today().isoformat()

    print(f"\n{'[DRY RUN] ' if dry_run else ''}Creating skill: {skill_name}")
    print(f"  Location : {skill_dir}")
    print(f"  Category : {category}")
    print()

    files: dict[Path, str] = {}

    # SKILL.md
    files[skill_dir / "SKILL.md"] = f"""\
---
name: {skill_name}
description: {description} Use when [TODO: add trigger phrases]. Do NOT use for [TODO: add negative triggers].
compatibility: [TODO: note any network or tool requirements, or remove this line]
metadata:
  author: [TODO: your name]
  version: 1.0.0
  category: {category}
  tags: [{skill_name}, TODO]
---

# {skill_name.replace("-", " ").title()}

[TODO: one-line overview]

## When to Use

- [TODO: trigger scenario 1]
- [TODO: trigger scenario 2]

**Do not use for**: [TODO: negative triggers]

## Instructions

### Step 1: [TODO: step name]

[TODO: what to DO — not just what to know]

### Step 2: [TODO: step name]

[TODO: ...]

## Examples

### Example 1: [TODO: short name]

User asks: "[TODO: realistic user prompt]"

Response:
1. [TODO: ...]

## Notes

- [TODO: edge cases, caveats, API limits]
"""

    # CHANGELOG.md
    files[skill_dir / "CHANGELOG.md"] = f"""\
# Changelog

All notable changes to {skill_name} are documented here.

A **breaking change** is any modification that causes the agent to behave
differently on previously-working queries.

## [1.0.0] - {today}

### Added
- Initial release
"""

    # scripts/ placeholder
    files[skill_dir / "scripts" / f"{skill_name.replace('-', '_')}.py"] = f"""\
#!/usr/bin/env python3
\"\"\"{skill_name} — {description}

Generated by create_skill.py. Replace this with real implementation.
See references/non-interactive-patterns.md for CI-safe input patterns.
\"\"\"

import sys
import os
import argparse
from pathlib import Path


def is_non_interactive() -> bool:
    return (
        not sys.stdin.isatty() or
        bool(os.getenv("CI")) or
        bool(os.getenv("GITHUB_ACTIONS")) or
        bool(os.getenv("AUTOMATED_MODE"))
    )


def safe_input(prompt: str, default: str | None = None,
               choices: list[str] | None = None) -> str:
    if is_non_interactive():
        return choices[0] if choices else (default or "auto")
    try:
        response = input(prompt).strip()
        if choices and response not in choices:
            print(f"Invalid. Options: {{choices}}")
            return safe_input(prompt, default, choices)
        return response if response else (default or "")
    except (EOFError, KeyboardInterrupt):
        return default or ""


def main() -> None:
    parser = argparse.ArgumentParser(description="{description}")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    try:
        run(args)
    except KeyboardInterrupt:
        print("\\nCancelled.")
        sys.exit(0)
    except Exception as exc:
        print(f"Error: {{exc}}")
        sys.exit(1)


def run(args: argparse.Namespace) -> None:
    print(f"Running {skill_name}...")
    # TODO: implement skill logic
    # Use safe_input() for any user prompts
    # Use is_non_interactive() to skip interactive enhancements in CI


if __name__ == "__main__":
    main()
"""

    # evals/ stubs
    files[skill_dir / "evals" / "evals.json"] = f"""\
{{
  "skill_name": "{skill_name}",
  "evals": [
    {{
      "id": 1,
      "name": "TODO-eval-name",
      "prompt": "TODO: concrete user prompt with real context, file names, etc.",
      "expected_output": "TODO: one sentence describing success",
      "files": [],
      "expectations": [
        "TODO: verifiable assertion — prefer content checks over existence checks",
        "TODO: another assertion"
      ]
    }}
  ]
}}
"""

    files[skill_dir / "evals" / "trigger-evals.json"] = """\
[
  {"query": "TODO: concrete should-trigger query", "should_trigger": true},
  {"query": "TODO: another should-trigger query", "should_trigger": true},
  {"query": "TODO: near-miss should-NOT-trigger query", "should_trigger": false},
  {"query": "TODO: another near-miss query", "should_trigger": false}
]
"""

    if dry_run:
        print("Files that would be created:")
        for path in sorted(files):
            print(f"  {path.relative_to(SKILLS_ROOT)}")
        return skill_dir

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"  created {path.relative_to(SKILLS_ROOT)}")

    # Make script executable
    script = skill_dir / "scripts" / f"{skill_name.replace('-', '_')}.py"
    script.chmod(0o755)

    print(f"\n✅  Scaffold created at {skill_dir}")
    print()
    print("Next steps:")
    print(f"  1. Edit {skill_name}/SKILL.md — fill in all [TODO] markers")
    print(f"  2. Fill in evals/evals.json and evals/trigger-evals.json")
    print(f"  3. Run skill-evaluator to baseline before iterating")
    print(f"  4. Load references/spec.md and run the quality checklist")

    return skill_dir


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Scaffold a new skill directory following the skill spec.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("name", help="Skill name — will be normalised to kebab-case")
    parser.add_argument("description", help="One-sentence description")
    parser.add_argument(
        "--category",
        default="utility",
        choices=CATEGORIES,
        help=f"Skill category (default: utility). Options: {', '.join(CATEGORIES)}",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help=f"Skills root directory (default: {SKILLS_ROOT})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be created without writing any files",
    )
    args = parser.parse_args()

    global SKILLS_ROOT
    if args.output_dir:
        SKILLS_ROOT = Path(args.output_dir)

    try:
        create_skill(args.name, args.description, args.category, args.dry_run)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nCancelled.")
        sys.exit(0)


if __name__ == "__main__":
    main()
